### ISSUE TITLE
[Feature Request] Support for Finding AsyncDisplayKit Nodes

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/chisel#145]
https://github.com/facebook/AsyncDisplayKit is an incredible framework, and any non-trivial app would benefit from using it. Would it be possible to add a `fnode` or equivalent that finds the view (layer, even?!) that hosts a node of a given class?

I know ASDK code pretty well, so I can help if needed with the actual "find the node in the view hierarchy" code.

**Comment by kastiglione** [comment]
Sounds doable. Does it require traversing the view tree, or is there any "index" from nose to host?

**Comment by Adlai-Holler** [comment]
Sweet, thanks for offering to help with this!

You've actually got to traverse the layer tree. Some nodes are backed by UIViews and others by raw CALayers. There's a private `-[CALayer asyncdisplaykit_node]` method to get the associated node, if any, for a layer. In Swift, I can't call that method from lldb since it's private =( we could use `valueForKey:"asyncdisplaykit_node"` which would work from Swift or Obj-C lldb frames but is a little uglier.

ASDisplayNode also has a `name` property. It's not very commonly used tbh but it'd be great to support searching by class or by name (pattern?).

**Comment by kastiglione** [comment]
What do you think about adding private methods in ASDK for Chisel to call? We could do it all via Python/lldb, but the benefits to having the heavy lifting done by the library are:

1. The command will run faster
2. If there are breaking changes to internals, the support code will get updated with it
3. The code can optionally be tested

Where available, Chisel will call available private debugging helper methods. In some cases, we have a fallback implementation inside Chisel.

So the choice to make is, do we implement the tree traversal in:

1. ASDK
2. Chisel
3. Both

I would suggest no. 1 for long term, and maybe no. 3 at the start since people might be using an ASDK version that doesn't contain the debugging helpers.

**Comment by Adlai-Holler** [comment]
There exists a function:

```objectivec
NSArray<ASDisplayNode *> *ASDisplayNodeFindAllSubnodes(ASDisplayNode *start, BOOL (^block)(ASDisplayNode *node))
```

which is perfect except that it requires a start node, which we don't have. The more general version of that function:

```objectivec
ASDisplayNodePerformBlockOnEveryNode(CALayer *layer, ASDisplayNode *node, void(^block)(ASDisplayNode *node))
```

accepts a layer or a node, so we could call that with e.g. the layer of the key window, right? Those functions have been around for a long time, so if they're sufficient then no. 1 is the way to go.

@appleguy Thoughts?

**Comment by appleguy** [comment]
I recently learned that ASDisplayNodeExtras.h is _technically_ public, which wasn't really intended...lol.  It contains the needed functionality, such as:

/**
 Given a layer, returns the associated display node, if any.
 */
extern ASDisplayNode * _Nullable ASLayerToDisplayNode(CALayer * _Nullable layer);

/**
 Given a view, returns the associated display node, if any.
 */
extern ASDisplayNode * _Nullable ASViewToDisplayNode(UIView * _Nullable view);

That said, I'd be thrilled to add any private functionality we'd like to support chisel.  @kastiglione, very grateful to have your support on this.  Since every iOS developer at Pinterest is using ASDK, we'll add 25-30 Chisel users overnight once this is available :).

**Comment by kastiglione** [comment]
@Adlai-Holler @appleguy I lost track of this one, sorry about that. Is this still something you're interested in? If yes, has any of the technical details changed in the last couple months?

**Comment by kastiglione** [comment]
This is something that `findinstances` should be able to do. Please reopen or @ mention me to discuss this more.
